on: [push]
name: deploy
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: "dist/"
          server-dir: "pfxr/"
